#  Copyright 2016  C.S.I.R. Meraka Institute.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Meant to be run in a container

---
- name: Ensure mysql client is present
  become: true
  package:
    name: "{{ item }}"
  with_items: "{{ prereq[ansible_os_family] }}"

- name: get the source code
  git:
    repo: https://github.com/brucellino/fgAPIServer
    dest: "{{ install_path }}"
    force: yes

- name: Install URLlib3 (CentOS6)
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ extra_pips }}"
  # when:
  #   ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'
- name: install python requirements
  become: true
  pip:
    requirements: "{{ install_path }}/requirements.txt"

- name: Apply configuration template.
  template:
    src: fgapiserver.conf.j2
    dest: "{{ install_path }}/fgapiserver.conf"

- name: start the server
  command: python fgapiserver.py
  args:
    chdir: "{{ install_path }}"
